/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_joc_jguii_Application */

#ifndef _Included_com_joc_jguii_Application
#define _Included_com_joc_jguii_Application
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_joc_jguii_Application
 * Method:    windowSearch
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_joc_jguii_Application_windowSearch
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_joc_jguii_Application
 * Method:    setWindowFocus
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_joc_jguii_Application_setWindowFocus
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_joc_jguii_ApplicationHandler */

#ifndef _Included_com_joc_jguii_ApplicationHandler
#define _Included_com_joc_jguii_ApplicationHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_joc_jguii_ApplicationHandler
 * Method:    windowSearch
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_joc_jguii_ApplicationHandler_windowSearch
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_joc_jguii_ApplicationHandler
 * Method:    getWindowFocus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_joc_jguii_ApplicationHandler_getWindowFocus
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_joc_jguii_ConfigHandler */

#ifndef _Included_com_joc_jguii_ConfigHandler
#define _Included_com_joc_jguii_ConfigHandler
#ifdef __cplusplus
extern "C" {
#endif
#undef com_joc_jguii_ConfigHandler_maxSkipBufferSize
#define com_joc_jguii_ConfigHandler_maxSkipBufferSize 8192L
#undef com_joc_jguii_ConfigHandler_INVALIDATED
#define com_joc_jguii_ConfigHandler_INVALIDATED -2L
#undef com_joc_jguii_ConfigHandler_UNMARKED
#define com_joc_jguii_ConfigHandler_UNMARKED -1L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_joc_jguii_InteractionHandler */

#ifndef _Included_com_joc_jguii_InteractionHandler
#define _Included_com_joc_jguii_InteractionHandler
#ifdef __cplusplus
extern "C" {
#endif
#undef com_joc_jguii_InteractionHandler_MAX_DELAY
#define com_joc_jguii_InteractionHandler_MAX_DELAY 60000L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_joc_jguii_NamedPoint */

#ifndef _Included_com_joc_jguii_NamedPoint
#define _Included_com_joc_jguii_NamedPoint
#ifdef __cplusplus
extern "C" {
#endif
#undef com_joc_jguii_NamedPoint_serialVersionUID
#define com_joc_jguii_NamedPoint_serialVersionUID -5276940640259749850LL
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_joc_jguii_Test */

#ifndef _Included_com_joc_jguii_Test
#define _Included_com_joc_jguii_Test
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
